/*
  LOCAL
*/

/*
  SERVER
*/
export const GET_RECIPE_MEAL_PLANS_GENERATE_START =
  'RECIPE/GET_RECIPE_MEAL_PLANS_GENERATE_START';
export const GET_RECIPE_MEAL_PLANS_GENERATE_SUCCESS =
  'RECIPE/GET_RECIPE_MEAL_PLANS_GENERATE_SUCCESS';
export const GET_RECIPE_MEAL_PLANS_GENERATE_ERROR =
  'RECIPE/GET_RECIPE_MEAL_PLANS_GENERATE_ERROR';
